### ISSUE TITLE
Developing support for multiple image viewing with indicators for image registration like display of the borders, and display lines connecting points.

### ISSUE THREAD

**Issue by jakubMitura14** [JuliaHealth/MedEye3d.jl#4]
Success criteria 
The user can load 2 different images, and they would display concurrently one next to the other. During scrolling the same area of the body should be displayed (for well-registered sample images) based on the supplied metadata. While moving the mouse cursor on one image the position of the cursor in the same physical spot on the other image should be displayed (physical location calculated from spatial metadata).

**Comment by divital-coder** [comment]
Addressed in GSOC PR
