### ISSUE TITLE
Support of display for supervoxels (sv). Show borders of sv; indicate whether the gradient of the image is in agreement with sv borders

### ISSUE THREAD

**Issue by jakubMitura14** [JuliaHealth/MedEye3d.jl#6]
Success when 
Given an integer mask where a unique integer value will encode information about a single supervoxel and an underlying 3d medical image user will have the option to overlay the original image with the borders of the superpixels where adjacent borders will have different colors, or show those borders on the background of the image convolved with edge filter, for example, Sobel filter

**Comment by divital-coder** [comment]
Addressed in GSOC PR
